### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by krystynakono** [krmalewski/the_moodie_foodie#1]
# The Moodie Foodie

## Concept 
Too hungry to make a decision about where to eat? Moodie Foodie is here to help. Take a short quiz when signing up and whenever you are looking for some place to go eat, tell Moodie Foodie your current mood and it will suggest a restaurant to go to that best matched with your mood and current location. 

## Technology
React
Yelp API
Google Maps API
Node

## User Story
When creating an account for this app, user will take a short quiz on what types of foods they associate with different emotions. After logging in, user will select their current mood from a drop down menu. The Moodie Foodie will use geolocation to determine their current location and suggest a random restaurant with the type of cuisine that they best associate with the particular emotion they are feeling at the moment. User can save the restaurant for a later date or can pass completely and try again. User can view a list of all saved restaurants. 

### Sign Up
[Link to sign up page wireframe](https://wireframe.cc/HuxfFn)

### Main Page
[Link to main page wireframe](https://wireframe.cc/Dxr2kc)

## Timeline
By the end of Thursday: Have App and basic components mapped out
By the end of Friday: Get yelp API working and searchable
By the end of Saturday: Get geolocation working when user searches with Yelp
By the end of Sunday: Get user auth working
By the end of Monday: Google maps rendering to page
Tuesday and Wednesday are styling/buffer days. 

## Key Challenges
- User auth for the signup
- OAuth with Yelp

@rapala61 @gittheking @jasonseminara @irwintsay @trevorpreston

**Comment by gittheking** [comment]
@krmalewski  approved!

**Comment by rapala61** [comment]
Hi Krystyna, can you close this issue, please? Thanks!
