### ISSUE TITLE
Heroku Deployment 

### ISSUE THREAD

**Issue by krystynakono** [krmalewski/the_moodie_foodie#5]
I am trying to deploy my app to Heroku but am unsuccessful. 

I keep getting an error "cannot find module 'dotenv'. When I placed 'dotenv' in dependencies, I am getting an application error on the site even though it says the build was successful. When I placed 'dotenv' in devdependencies my applications says "Cannot GET /" after a "successful build". 

@rapala61 @gittheking @jasonseminara @irwintsay @trevorpreston

**Comment by trevorpreston** [comment]
@jasonseminara is giving a lesson on deployment today that should hopefully clear this up.

**Comment by krystynakono** [comment]
great, thanks! @trevorpreston
